// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(FootballContext))]
    [Migration("20240920223302_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Data.Models.MatchData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("TEXT");

                    b.Property<float?>("AwayWin")
                        .HasColumnType("REAL");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Draw")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("TEXT");

                    b.Property<float?>("HomeWin")
                        .HasColumnType("REAL");

                    b.Property<float?>("OverFourGoals")
                        .HasColumnType("REAL");

                    b.Property<float?>("OverOneGoal")
                        .HasColumnType("REAL");

                    b.Property<float?>("OverThreeGoals")
                        .HasColumnType("REAL");

                    b.Property<float?>("OverTwoGoals")
                        .HasColumnType("REAL");

                    b.Property<float?>("UnderFourGoals")
                        .HasColumnType("REAL");

                    b.Property<float?>("UnderOneGoal")
                        .HasColumnType("REAL");

                    b.Property<float?>("UnderThreeGoals")
                        .HasColumnType("REAL");

                    b.Property<float?>("UnderTwoGoals")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MatchData");
                });
#pragma warning restore 612, 618
        }
    }
}
